baseURL = 'https://turkeystar142.github.io/cookdex/'
theme = 'cookdex'
defaultContentLanguage = 'en'

[languages.en]
  languageCode = 'en-us'
  languageName = 'English'
  title = 'Cookdex'
  weight = 1
  contentDir = 'content/en'

[languages.es]
  languageCode = 'es'
  languageName = 'Espa√±ol'
  title = 'Cookdex'
  weight = 2
  contentDir = 'content/es'
