baseURL = 'https://example.com/'
theme = 'cookdex'
defaultContentLanguage = 'en'
title = 'Cookdex Recipe Collection'

[languages.en]
  languageCode = 'en-us'
  languageName = 'English'
  title = 'Cookdex Recipe Collection'
  weight = 1
  contentDir = 'content/en'

[languages.es]
  languageCode = 'es'
  languageName = 'Español'
  title = 'Colección de Recetas Cookdex'
  weight = 2
  contentDir = 'content/es'
